# Generated by Django 3.1.5 on 2021-01-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0002_auto_20210111_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_drivers', 'Access to add Drivers'), ('can_remove_drivers', 'Access to remove Drivers'))},
        ),
    ]
