# Generated by Django 3.1.5 on 2021-01-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0003_auto_20210111_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_drivers', 'Access to add Drivers'), ('can_remove_drivers', 'Access to remove Drivers'), ('can_update_drivers', 'Access to update Drivers'), ('can_add_location', 'Access to add location'), ('can_remove_location', 'Access to remove location'), ('can_update_location', 'Access to update location'))},
        ),
    ]
