# Generated by Django 3.1.5 on 2021-01-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0004_auto_20210111_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
