# Generated by Django 3.1.5 on 2021-01-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0010_auto_20210113_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='product_images',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
