# Generated by Django 3.1.5 on 2021-01-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0013_auto_20210113_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Images', to='DaanpatraApp.donation'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
