# Generated by Django 3.1.5 on 2021-01-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0015_funddonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddonation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='funddonation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
