# Generated by Django 3.1.5 on 2021-01-15 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0018_auto_20210114_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='assign_to',
        ),
        migrations.AddField(
            model_name='donation',
            name='assign_to_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_to_drivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='assign_to_sub_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_to_Sub_Admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
