# Generated by Django 3.1.5 on 2021-01-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0019_auto_20210115_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Super_Admin', 'Super Admin'), ('Sub_Admin', 'Sub Admin'), ('driver', 'Driver'), ('user', 'User')], default='user', max_length=30),
        ),
    ]
