# Generated by Django 3.1.5 on 2021-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0021_delete_funddonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Profile Pictures'),
        ),
    ]
