# Generated by Django 3.1.5 on 2021-01-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0023_auto_20210116_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Donation Product Image'),
        ),
    ]
