# Generated by Django 3.1.5 on 2021-01-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0024_auto_20210120_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
