# Generated by Django 3.1.5 on 2021-02-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0027_auto_20210129_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='Donation Gallery')),
            ],
        ),
    ]
