# Generated by Django 3.1.5 on 2021-02-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaanpatraApp', '0030_auto_20210206_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
